kind: pipeline
name: default

steps:
  - name: test
    image: node:10-alpine
    commands:
      - npm install
      - npm run build
    when:
    branch:
      - master
    event:
      - push
      - pull-request

  - name: deploy
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      VUE_APP_AUTH_SERVICE:
        from_secret: VUE_APP_AUTH_SERVICE
      VUE_APP_PUSH_SERVICE:
        from_secret: VUE_APP_PUSH_SERVICE
      VUE_APP_SCHEDULE_SERVICE:
        from_secret: VUE_APP_SCHEDULE_SERVICE
      VUE_APP_apiKey:
        from_secret: VUE_APP_apiKey
      VUE_APP_authDomain:
        from_secret: VUE_APP_authDomain
      VUE_APP_databaseURL:
        from_secret: VUE_APP_databaseURL
      VUE_APP_projectId:
        from_secret: VUE_APP_projectId
      VUE_APP_storageBucket:
        from_secret: VUE_APP_storageBucket
      VUE_APP_messagingSenderId:
        from_secret: VUE_APP_messagingSenderId
      VUE_APP_publicVapidKey:
        from_secret: VUE_APP_publicVapidKey
      PORT: 3000
    settings:
      build_args_from_env:
      - VUE_APP_AUTH_SERVICE
      - VUE_APP_PUSH_SERVICE
      - VUE_APP_SCHEDULE_SERVICE
      - VUE_APP_apiKey
      - VUE_APP_authDomain
      - VUE_APP_databaseURL
      - VUE_APP_projectId
      - VUE_APP_storageBucket
      - VUE_APP_messagingSenderId
      - VUE_APP_publicVapidKey
      - PORT
    commands:
      - docker build -t nick/vestra .
      - docker rmi $(docker images -f "dangling=true" -q)
      - docker container stop vestra || true && docker rm vestra || true
      - docker run --volumes-from /usr/share/nginx/html -e VUE_APP_AUTH_SERVICE=$VUE_APP_AUTH_SERVICE -e VUE_APP_PUSH_SERVICE=$VUE_APP_PUSH_SERVICE -e VUE_APP_SCHEDULE_SERVICE=$VUE_APP_SCHEDULE_SERVICE -e VUE_APP_apiKey=$VUE_APP_apiKey -e VUE_APP_authDomain=$VUE_APP_authDomain -e VUE_APP_databaseURL=$VUE_APP_databaseURL -e VUE_APP_projectId=$VUE_APP_projectId -e VUE_APP_storageBucket=$VUE_APP_storageBucket -e VUE_APP_messagingSenderId=$VUE_APP_messagingSenderId -e VUE_APP_publicVapidKey=$VUE_APP_publicVapidKey -p 6443:3000 -d --name=vestra nick/vestra

  - name: telegram
    image: appleboy/drone-telegram:latest
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_user_id
      message: >
      format: html
      message: >
        {{#success build.status}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a> 
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{else}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{/success}}
    when:
      status: [success, failure]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock