kind: pipeline
name: default

steps:
  - name: test
    image: node:12-alpine
    commands:
      - npm install
      - npm run build
    environment:
      VUE_APP_AUTH_SERVICE:
        from_secret: VUE_APP_AUTH_SERVICE
      VUE_APP_PUSH_SERVICE:
        from_secret: VUE_APP_PUSH_SERVICE
      VUE_APP_SCHEDULE_SERVICE:
        from_secret: VUE_APP_SCHEDULE_SERVICE
      VUE_APP_apiKey:
        from_secret: VUE_APP_apiKey
      VUE_APP_authDomain:
        from_secret: VUE_APP_authDomain
      VUE_APP_databaseURL:
        from_secret: VUE_APP_databaseURL
      VUE_APP_projectId:
        from_secret: VUE_APP_projectId
      VUE_APP_storageBucket:
        from_secret: VUE_APP_storageBucket
      VUE_APP_messagingSenderId:
        from_secret: VUE_APP_messagingSenderId
      VUE_APP_publicVapidKey:
        from_secret: VUE_APP_publicVapidKey
      VUE_APP_MARKS_SERVICE:
        from_secret: VUE_APP_MARKS_SERVICE
      PORT: 3000
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: deploy
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t nick/vestra .
      - docker rmi -f $(docker images -f "dangling=true" -q) || true
      - docker container stop vestra || true && docker rm vestra || true
      - docker run -v /usr/share/nginx/html:/usr/share/nginx/html -p 6443:3000 -d --name=vestra nick/vestra
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: telegram
    image: appleboy/drone-telegram:latest
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_user_id
      message: >
      format: html
      message: >
        {{#success build.status}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">SUCCESS</a> 
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{else}}
          <code>{{repo.owner}}/{{repo.name}}</code> <a href="{{build.link}}">FAILURE</a>
          <code>{{commit.branch}}</code>@<a href="{{commit.link}}">{{truncate commit.sha 7}}</a>
        {{/success}}
    when:
      status: [success, failure]

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock